//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionDiagnostics.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotionDiagnostics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   얼라인을 시작하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_CONFIRM_START_ALIGN {
            get {
                return ResourceManager.GetString("MB_MSG_CONFIRM_START_ALIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장치가 연결되지 않았습니다. 장치 연결 후 다시 실행하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_DEVICE_IS_NOT_RUNNING {
            get {
                return ResourceManager.GetString("MB_MSG_DEVICE_IS_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 로딩을 완료 하셨습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_LOADING_COMPLETED {
            get {
                return ResourceManager.GetString("MB_MSG_LOADING_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택 영역에 대한 스텝 측정을 시작하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_MEASURE {
            get {
                return ResourceManager.GetString("MB_MSG_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   측정이 취소되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_MEASURE_CANCELED {
            get {
                return ResourceManager.GetString("MB_MSG_MEASURE_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   측정 위치가 선택되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_MEASURE_NOSELECTION {
            get {
                return ResourceManager.GetString("MB_MSG_MEASURE_NOSELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 중앙 위치로 이동 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_MOVE_TO_CENTER_POSITION {
            get {
                return ResourceManager.GetString("MB_MSG_MOVE_TO_CENTER_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 왼쪽 가장자리로 이동 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_MOVE_TO_LEFT_EDGE_POSITION {
            get {
                return ResourceManager.GetString("MB_MSG_MOVE_TO_LEFT_EDGE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 로딩/언로딩 위치로 이동 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_MOVE_TO_LOADING_POSITION {
            get {
                return ResourceManager.GetString("MB_MSG_MOVE_TO_LOADING_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 오른쪽 가장자리로 이동 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_MOVE_TO_RIGHT_EDGE_POSITION {
            get {
                return ResourceManager.GetString("MB_MSG_MOVE_TO_RIGHT_EDGE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비전 카메라를 라이브 상태로 변경하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_NEED_TO_GRAB_IMAGE {
            get {
                return ResourceManager.GetString("MB_MSG_NEED_TO_GRAB_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 위치가 중앙 위치가 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_POS_IS_NOT_CENTER {
            get {
                return ResourceManager.GetString("MB_MSG_POS_IS_NOT_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 위치가 왼쪽 가장자리가 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_POS_IS_NOT_LEFTEDGE {
            get {
                return ResourceManager.GetString("MB_MSG_POS_IS_NOT_LEFTEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 위치가 오른쪽 가장자리가 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_POS_IS_NOT_RIGHTEDGE {
            get {
                return ResourceManager.GetString("MB_MSG_POS_IS_NOT_RIGHTEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복 측정을 진행 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_REPEATMEASURE {
            get {
                return ResourceManager.GetString("MB_MSG_REPEATMEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 반복 측정이 취소되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_REPEATMEASURE_CANCELED {
            get {
                return ResourceManager.GetString("MB_MSG_REPEATMEASURE_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 반복 측정이 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_REPEATMEASURE_FAILED {
            get {
                return ResourceManager.GetString("MB_MSG_REPEATMEASURE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 반복 측정이 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_REPEATMEASURE_SUCCESS {
            get {
                return ResourceManager.GetString("MB_MSG_REPEATMEASURE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼를 설정한 각도만큼 회전 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_ROTATION_ANGLE {
            get {
                return ResourceManager.GetString("MB_MSG_ROTATION_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 중앙위치로 현재 위치를 저장 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_SAVE_CENTER_MARK {
            get {
                return ResourceManager.GetString("MB_MSG_SAVE_CENTER_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   좌측 가장자리로 현재 위치를 저장 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_SAVE_LEFTEDGE_MARK {
            get {
                return ResourceManager.GetString("MB_MSG_SAVE_LEFTEDGE_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   우측 가장자리로 현재 위치를 저장 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_SAVE_RIGHTEDGE_MARK {
            get {
                return ResourceManager.GetString("MB_MSG_SAVE_RIGHTEDGE_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼를 스테이지에서 언로딩 하셨습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_UNLOADING_COMPLETED {
            get {
                return ResourceManager.GetString("MB_MSG_UNLOADING_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 얼라인을 진행 중입니다. 잠시만 기다려 주십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_MSG_WAFER_ALIGN {
            get {
                return ResourceManager.GetString("MB_MSG_WAFER_ALIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_TITLE_CONFIRM {
            get {
                return ResourceManager.GetString("MB_TITLE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 로딩 상태 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_TITLE_LOADING_COMPLETED {
            get {
                return ResourceManager.GetString("MB_TITLE_LOADING_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스텝 측정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_TITLE_MEASURE {
            get {
                return ResourceManager.GetString("MB_TITLE_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_TITLE_PROCESSING {
            get {
                return ResourceManager.GetString("MB_TITLE_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복 측정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_TITLE_REPEATMEASURE {
            get {
                return ResourceManager.GetString("MB_TITLE_REPEATMEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 얼라인 진행 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_TITLE_WAFER_ALIGN {
            get {
                return ResourceManager.GetString("MB_TITLE_WAFER_ALIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_TITLE_WARNING {
            get {
                return ResourceManager.GetString("MB_TITLE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디바이스를 초기화 하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_STANDBY_DEVICE_ATTACH {
            get {
                return ResourceManager.GetString("MSG_STANDBY_DEVICE_ATTACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 측정이 준비 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_STANDBY_MEASURE_READY {
            get {
                return ResourceManager.GetString("MSG_STANDBY_MEASURE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모터를 초기화 하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_STANDBY_MOTION_INIT {
            get {
                return ResourceManager.GetString("MSG_STANDBY_MOTION_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비전 카메라가 준비되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_STANDBY_VISION_NOT_READY {
            get {
                return ResourceManager.GetString("MSG_STANDBY_VISION_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 얼라인을 완료하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_STANDBY_WAFER_ALIGN_NOT_READY {
            get {
                return ResourceManager.GetString("MSG_STANDBY_WAFER_ALIGN_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웨이퍼 로딩을 완료하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MSG_STANDBY_WAFER_LOADING_NOT_COMPLETED {
            get {
                return ResourceManager.GetString("MSG_STANDBY_WAFER_LOADING_NOT_COMPLETED", resourceCulture);
            }
        }
    }
}
