// <auto-generated />
using EPLE.Data;
using EntityFrameworkCore.Jet.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EPLE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241223012347_AddTest")]
    partial class AddTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EPLE.Data.Entity.DataConfigEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<int>("DataResetTimeout")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("longchar");

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Group")
                        .HasColumnType("longchar");

                    b.Property<string>("Module")
                        .HasColumnType("longchar");

                    b.Property<int>("PollingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("UpdateTime")
                        .HasColumnType("longchar");

                    b.Property<bool>("Use")
                        .HasColumnType("smallint");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Data", (string)null);
                });

            modelBuilder.Entity("EPLE.Data.Entity.DeviceConfigEntity", b =>
                {
                    b.Property<string>("DeviceName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("longchar");

                    b.Property<bool>("Use")
                        .HasColumnType("smallint");

                    b.HasKey("DeviceName");

                    b.ToTable("Device", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
